name: Deploy GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Pages
        uses: actions/configure-pages@v3

      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: .

      - name: Download HTML
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
